#+TITLE: persona.el
#+AUTHOR: LordYuuma

* Installation
  ~git clone~ this library or just download ~persona.el~ and put it
  somewhere into your ~load-path~.

* Widgets
** persona
   Mimics the look and feel of the custom face widget, without
   attaching it to a face.
   To work together with ~personae~, faces in ~:inherit~ may also
   be symbol lists.
** personae
   Groups multiple ~persona~ widgets together, with potential recursion.
* Functions
** persona-face-or-unmask ~(face-or-persona)~
   Takes a single face, symbol or list of symbols as argument and
   returns a symbol, which may be a face (or ~nil~), if the argument is
   of a wrong type).
** persona-attributes-to-face ~(attributes)~
   Takes a list of persona attributes (the persona equivalent to face
   attributes) and maps them to face attributes. Instead of calling this
   function directly, you are likely looking for ~persona-declare-face~
   or ~persona-unmask-and-declare~.
** persona-declare-face ~(symbol persona doc &rest args)~
   Simple wrapper around ~custom-declare-face~ transforming persona
   attributes to face attributes.
** personae-unmask-and-declare ~(personae)~
   Recursively applies ~persona-declare-face~, using
   ~personae-infer-documentation-function~ to infer documentation and
   ~personae-infer-group-function~ to infer group tags.
* Variables
** personae-infer-documentation-function ~(lambda (symbols) some-doc)~
   Can be used in ~persona-unmask-and-declare~ to override the default
   documentation of a declared face.
** personae-infer-group-function ~(lambda (symbol) some-group)~
   Can be used in ~persona-unmask-and-declare~ to override the default
   group of a declared face.
